Reprocessing overall_scores 
Jira Ticket: https://sagebionetworks.jira.com/browse/AG-220

Tasks:
- Subtract flyneuropath scores from logsdon scores
- include ensembl_gene_id

In [14]:
import synapseclient
import pandas as pd

syn = synapseclient.Synapse()
syn.login(silent=True)

interesting_columns = ['ENSG', 'GeneName', 'Logsdon', 'GeneticsScore', 'OmicsScore', 'LiteratureScore', 'FlyNeuroPathScore']

overall_scores = 'syn25575156'
overall_scores = syn.tableQuery(f'SELECT * FROM {overall_scores}').asDataFrame()
overall_scores = overall_scores[interesting_columns]

overall_scores

,ENSG,GeneName,Logsdon,GeneticsScore,OmicsScore,LiteratureScore,FlyNeuroPathScore
86948_92,ENSG00000273079,GRIN2B,7.165803,2.141011,1.686699,1.33809230769231,2.000000
86949_92,ENSG00000149269,PAK1,6.832003,1.561365,1.991869,1.27876923076923,2.000000
86950_92,ENSG00000180900,SCRIB,6.737554,1.618243,1.988317,1.79766153846154,1.333333
86951_92,ENSG00000116096,SPR,6.720777,1.723829,1.976886,1.02006153846154,2.000000
86952_92,ENSG00000124795,DEK,6.688744,1.499666,1.996955,1.19212307692308,2.000000
...,...,...,...,...,...,...,...
116010_119,ENSG00000269337,NaN,0.000000,0.000000,0.000000,0,0.000000
116011_119,ENSG00000272225,NaN,0.000000,0.000000,0.000000,0,0.000000
116012_119,ENSG00000225210,NaN,0.000000,0.000000,0.000000,0,0.000000
116013_119,ENSG00000249054,NaN,0.000000,0.000000,0.000000,0,0.000000
116014_119,ENSG00000268640,NaN,0.000000,0.000000,0.000000,0,0.000000

In [15]:
# subtract the FlyNeuroPathScore from Logsdon
overall_scores['Logsdon'] = overall_scores['Logsdon'] - overall_scores['FlyNeuroPathScore']
overall_scores.drop(columns=['FlyNeuroPathScore'], inplace=True)
overall_scores

,ENSG,GeneName,Logsdon,GeneticsScore,OmicsScore,LiteratureScore
86948_92,ENSG00000273079,GRIN2B,5.165803,2.141011,1.686699,1.33809230769231
86949_92,ENSG00000149269,PAK1,4.832003,1.561365,1.991869,1.27876923076923
86950_92,ENSG00000180900,SCRIB,5.404221,1.618243,1.988317,1.79766153846154
86951_92,ENSG00000116096,SPR,4.720777,1.723829,1.976886,1.02006153846154
86952_92,ENSG00000124795,DEK,4.688744,1.499666,1.996955,1.19212307692308
...,...,...,...,...,...,...
116010_119,ENSG00000269337,NaN,0.000000,0.000000,0.000000,0
116011_119,ENSG00000272225,NaN,0.000000,0.000000,0.000000,0
116012_119,ENSG00000225210,NaN,0.000000,0.000000,0.000000,0
116013_119,ENSG00000249054,NaN,0.000000,0.000000,0.000000,0
116014_119,ENSG00000268640,NaN,0.000000,0.000000,0.000000,0

In [16]:
overall_scores.to_json('../output/overall_scores.json', orient='records', indent=2)